### ISSUE TITLE
Authenticated user should be able to trigger a build without requiring Token

### ISSUE THREAD

**Issue by jeff2001** [zionyx/jenkins-tray#34]
For some reason the WebClient does not trigger a build correctly when specifying a user and password, forcing the use of the Token Method(This is undesirable as it means each job has to be set up correctly with a token and is not just a jenkins wide fix).

The snippet below is a crude fix to get it working, I havent bothered to create a pull request as I think someone with better knowledge will probably want to rewrite it. It is a method I called from inside 
```C#
public void RunBuild(Project project)
````

 I used https://github.com/csnate/cctray-jenkins-transport to get an idea of how to get it working.

```C#
        private string DownLoadStringBuild(Credentials credentials, string url)
        {
          string res;
          var request = (HttpWebRequest)WebRequest.Create(url);
          if (!String.IsNullOrEmpty(credentials.Username))
          {
            request.Headers["Authorization"] = "Basic " +
                                               Convert.ToBase64String(
                                                 Encoding.Default.GetBytes(String.Format("{0}:{1}", credentials.Username, credentials.Password)));

          }
          request.Referer = BaseUrl;
          request.Method = "POST";
          request.ContentType = "application/x-www-form-urlencoded";
          using (var response = request.GetResponse())
          {
            res = response.ResponseUri.ToString(); 
          }  

          return res;
      }
```

**Comment by jeff2001** [comment]
On further investigation it seems that the reason it was not working was that a build request should be an Upload(POST) not a Download. I have created a pull request with the fix.

**Comment by zionyx** [comment]
Thanks for the pull request. I was puzzled by it too. I'll investigate further and get back to you.

**Comment by zionyx** [comment]
Thanks alot for the codes, it worked really well.

However, in your pull request, there is an additional commit for release 1.0.1.1.
Can you only include this commit, https://github.com/jeff2001/jenkins-tray/commit/18d2844b2f612d02d43b084b897e9dc6c6629f71 ?

I'll make a quick release to 1.0.2 including whatever that was pushed to master so far, after accepting your new pull request. Thanks @jeff2001 !
