### ISSUE TITLE
Animated icon for projects in progress

### ISSUE THREAD

**Issue by zionyx** [zionyx/jenkins-tray#42]
As a user, it is very hard to differentiate an in progress project apart from the rest, which are not building.

The existing color icons are a little close to the next status. Animated icon, may be a good solution to this problem.

**Comment by jeff2001** [comment]
Not directly related but I was looking at changing the icons to a j not an
h to match with Jenkins

**Comment by zionyx** [comment]
I had that in mind since the beginning of the project. If you can come up with new sets of icons / images, that will be a great help. ;-)

The original resource file to generate the H icons are located in \resources\TrayIcons.pdn.

https://github.com/zionyx/jenkins-tray/issues/43

**Comment by zionyx** [comment]
https://github.com/zionyx/jenkins-tray/issues/43

**Comment by zionyx** [comment]
@jeff2001, please help review these icons. If you like it, i'll merge it to master soon. Thanks.

**Comment by jeff2001** [comment]
@zionyx Icons look good, sorry for the slow reply was away on holiday.

**Comment by zionyx** [comment]
No worries. Thanks for the response. 

I merged and closed this issue while working on #3. I just cant stand the existing icons when the project is building. It feels like nothing is happening.
