### ISSUE TITLE
Doubleclick on filter column border could perform "Best Fit"

### ISSUE THREAD

**Issue by GarthF** [zionyx/jenkins-tray#51]
Resizing the columns when doubleclicking on the column border using the "Best Fit" functionality available on right click of the columns would be a nice enhancement. Currently the doubleclick opens the output page of the first project in the list.
![2015-09-15_11-51-02](https://cloud.githubusercontent.com/assets/13380578/9873433/040ffe92-5ba0-11e5-9193-bdb414eb3b71.png)

**Comment by zionyx** [comment]
Relates to https://github.com/zionyx/jenkins-tray/issues/7

**Comment by zionyx** [comment]
Implemented best fit behavior.

However, something is not right when double clicking the column header edge on project name column when application starts. Hit detection gave wrong information, until details column header edge is best fitted. Weird.

You can have a test on this commit if it works like you intended.
https://ci.appveyor.com/project/zionyx/jenkins-tray-tracker/build/1.0.4.84/artifacts

Please let me know. Thanks.

**Comment by GarthF** [comment]
Agreed, that is weird behavior that the best fit only works after an initial re-size, but yes, the functionality after that is exactly what I was thinking.

**Comment by zionyx** [comment]
Thanks. I'll close the issue when it gets released.

**Comment by zionyx** [comment]
???... Waffle...
