### ISSUE TITLE
Installation error 2869 on Windows 10

### ISSUE THREAD

**Issue by zionyx** [zionyx/jenkins-tray#54]
Not sure what's causing the error.

**Comment by jeff2001** [comment]
I am running on win 10 with no issues.

**Comment by zionyx** [comment]
[JenkinsTrayInstall.log](https://github.com/zionyx/jenkins-tray/files/2063/JenkinsTrayInstall.log)
Hmm. Good to know.

I don't know what my colleague is missing from his machine. I'll have to find out. Here's the log file if it helps. Thanks.

**Comment by jeff2001** [comment]
The MSI error is 1603 from the log file.

From the web some causes may be:

Error 1603 occurs in one of the following conditions:

You are attempting to install Windows Installer to an encrypted folder.

The drive on which the folder to which you are attempting to install Windows Installer is located or accessed as a substitute drive on the system.

Windows Installer setup process uses the SYSTEM account to install the package to your computer. If the SYSTEM account does not have Full Control permissions on the folder to which you are installing the package, the error message will be displayed.

Hope that helps

**Comment by zionyx** [comment]
Thanks alot. I'll pay him a visit later to see if he has anything encrypted.

**Comment by zionyx** [comment]
Seems like a missing .Net Framwork 3.5 issue. Need to reproduce it to find out more.
Perhaps a bootstrapper could help.

**Comment by zionyx** [comment]
More issues:

I am having issues installing the latest version (1.0.4.1) on my newly re-installed W10 machine.
I am getting error 2869 under installation and it won't complete. 
Caught this in Windows Event Log:  
1.	Product: Jenkins Tray -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2869. The arguments are: ErrorDlg, , 
2.	The description for Event ID 11001 from source MsiInstaller cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
If the event originated on another computer, the display information had to be saved with the event.
The following information was included with the event:
Product: Jenkins Tray -- Error 1001. 
(NULL)
(NULL)
(NULL)
(NULL)
(NULL)
the message resource is present but the message is not found in the string/message table
3.	Windows Installer installed the product. Product Name: Jenkins Tray. Product Version: 1.0.4.1. Product Language: 1033. Manufacturer: Jenkins Tray Project. Installation success or error status: 1603.

**Comment by zionyx** [comment]
Confirmed that the missing .Net Framework 3.5 feature on Windows 10 causes this issue.
By enbling it, setup runs fine. 

 So this leads to the need for a bootstrapper for the installer to include / enable .Net Framework 3.5.

**Comment by szalapski** [comment]
Relevant: https://blogs.msdn.microsoft.com/oldnewthing/20110404-00/?p=11043

(Sent from my smartphone)

**Comment by zionyx** [comment]
I think the main cause of this issue is the installer requires process elevation in order to install files to Program Files folder, which requires additional effort in developing a bootstrapper for the setup. I am changing the approach to install the app to local user directory.

Adapting Squirrel.Windows over WiX as Squirrel is made just to install applications to local user directory. #77

**Comment by zionyx** [comment]
This issue will not be fixed. Future releases use Squirrel.Windows and has user wide installation. See #77.
