### ISSUE TITLE
Support Jenkins 2.73.1 by fixing the TLS

### ISSUE THREAD

**Issue by JeanFrancoeur** [zionyx/jenkins-tray#82]
Hi!  To be able to use the latest Jenkins version 2.73.1 with HTTPS, we need to fix the transport layer security.
Just one line of code to modify inside JenkinsService:
@389 ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

Thank you in advance,
Jean

**Comment by joha1712** [comment]
In my company we cannot make the tray tracker work with our production installation of Jenkins (which runs https and Jenkins v2.73.3) without this change. We get an error: "error loading projects". 

On our test environment (Jenkins v2.73.3) the tracker works fine, but here don´t use https.

I have looked at the source code on how to apply ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12. 

Sadly the code use DevXpress (which requires a developer license), so I could not make a hotfix. 
The code also has to be upgraded to .NET 4.5 to get access to SecurityProtocolType.Tls11 and SecurityProtocolType.Tls12. I hope this will be an easy task?

**Comment by zionyx** [comment]
Thanks. I'll make a quick release to address this issue asap. Hang in there.

**Comment by zionyx** [comment]
@joha1712, @JeanFrancoeur , if you can provide a pull request to this issue, that will make things a lot quicker. Thanks!

**Comment by JeanFrancoeur** [comment]
Hi!  When I made the pull request, it's linked to the master repo: https://github.com/aseigneurin/hudson-tray-tracker/pull/5    Thank you in advance

**Comment by zionyx** [comment]
@JeanFrancoeur, if you fork from this repo, then your commit / pull request will be based on this one. Anyway, i got your zip file.

It's nice to have your commit stamped in the repo so your contribution will not be gone unnoticed. :)

**Comment by zionyx** [comment]
Included in the upcoming release.
