### ISSUE TITLE
Restrict amount of data retrieved when requesting build info

### ISSUE THREAD

**Issue by sarchule** [zionyx/jenkins-tray#83]
This is related to a Jenkins issue (https://issues.jenkins-ci.org/browse/JENKINS-32860) affecting Jenkins running under Windows platforms. In short, if a build contains a large number of artifacts, then querying the build info takes a long time to process. The Tray Tracker exposes this issue since it is consistently querying the server for build info. A separate pull request was added to the original Hudson Tray Tracker (https://github.com/leapmotion/hudson-tray-tracker/compare/master...BernhardBerbuir:master) to limit the xml being returned via the tree directive -- but it appears this was never committed to a release. Requesting that a similar change be made to the jenkins-tray code. Noticed that the code does make use of the 'tree' directive in some cases, but it is not included within the BusinessComponents/JenkinsService.cs/GetBuildDetails() function--see pull request above for details.

Steps to reproduce:
1. create Jenkins job with large number of artifacts (windows platform)
2. query top level job info: jenkins/job/myjob/api/xml   -- processed very quickly
3. query specific build info (e.g., build 23): jenkins/job/myjob/23/api/xml  -- processed slowly since every artifact is listed - this causes problems with large set of requests (many tray tracker users and/or jobs)
4. solution: query specific build info using tree: jenkins/job/myjob/23/api/xml?tree=number,timestamp,builtOn,culprits[fullName],changeSet[items[*,author[id]]]   -- processed very quickly

**Comment by zionyx** [comment]
Hi @sarchule , thanks for raising this issue. Would appreciate if you can submit a pull request with this implemented. I am very close to a release before Christmas this year, so i hope the release train is able to grab this fix along.

You do not need any active DevExpress license to develop, build, debug and test the tray app. DevExpress license is only needed if you want to produce a release to users without the DevExpress trial dialog popping up when you run the tray app.

**Comment by zionyx** [comment]
Hi @sarchule, i'll get it included in a release before Christmas. Cheers.

**Comment by zionyx** [comment]
Included in the upcoming release.

**Comment by sarchule** [comment]
Thank you for your time and quick response in resolving this issue @zionyx !

**Comment by zionyx** [comment]
Tests failed and no build status is retrieved from the app. Reopening the issue for fixes.

**Comment by zionyx** [comment]
Fixed.
