### ISSUE TITLE
Implement Security Token

### ISSUE THREAD

**Issue by PaulSinnema** [zionyx/jenkins-tray#90]
We're using Jenkins on a domain server with ADFS Authentication. With the current implementation the application is unable to retrieve the list of projects from the server due to Authentication problems. I've cloned the project locally but can't change anything because of absence of the DevExpress environment.

**Comment by zionyx** [comment]
You can use your own API token as your password to authenticate with Jenkins Tray. The password and API token are used the same way but if you have enabled breadcrumb, that requires some additional work.

**Comment by zionyx** [comment]
I believe you can still work on the repository with a trial DevExpress license. Just not able to produce a release of the product without the DevExpress trial license dialog.

Kindly submit a PR if you have done changes that could benefit to the project. I can perhaps get some work done in these 2 weeks of my vacation. Cheers.

**Comment by PaulSinnema** [comment]
Hi,

 

Thanks for the quick reply. Creating a token in Jenkins and using that as my password works just fine.

 

Regards,

Paul Sinnema

 

Wageningen University & Research, Facilitair Bedrijf

Afdeling IT Informatie Systemen

Postbus 59, 6700 AB, Wageningen

 <http://www.wur.nl/nl/locatie/Actio.htm> Gebouw 116 (Actio), Akkermaalsbos 12, Wageningen

Tel. +31 6 133 707 45

 <mailto:paul.sinnema@wur.nl> paul.sinnema@wur.nl

 <https://www.linkedin.com/in/paulsinnema> https://www.linkedin.com/in/paulsinnema



 <http://www.disclaimer-nl.wur.nl/> http://www.disclaimer-nl.wur.nl/

**Comment by zionyx** [comment]
Glad that it works for you. Feel free to reopen the issue if you require further assistance. Cheers.
